from abc import ABC, abstractmethod

from app.backend.models.model_gateway import ModelGatewayRequest


class ModelAdapterError(RuntimeError):
    """Raised when a provider adapter cannot complete a model call."""


class ModelAdapter(ABC):
    @abstractmethod
    def generate_text(self, request: ModelGatewayRequest) -> str:
        """Return raw text generated by the provider."""

    @abstractmethod
    def generate_json(self, request: ModelGatewayRequest) -> str:
        """Return raw JSON text generated by the provider."""
